import { Product, LogEntry } from "@/hooks/useApi";

export type ModalMode = "view" | "edit";
export type ActiveTab = "ativos" | "desativados";
export type SortField = "name" | "price" | "stock" | null;
export type SortDir = "asc" | "desc";

export interface ProdutosContextType {
  products: Product[];
  activeProducts: Product[];
  inactiveProducts: Product[];
  loadingContent: boolean;
  activeTab: ActiveTab;
  setActiveTab: (tab: ActiveTab) => void;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  sortField: SortField;
  sortDir: SortDir;
  handleSort: (field: SortField) => void;
  isModalOpen: boolean;
  setIsModalOpen: (open: boolean) => void;
  modalMode: ModalMode;
  setModalMode: (mode: ModalMode) => void;
  productId: string | null;
  name: string;
  setName: (val: string) => void;
  price: string;
  setPrice: (val: string) => void;
  stock: string;
  setStock: (val: string) => void;
  minStock: string;
  setMinStock: (val: string) => void;
  category: string;
  setCategory: (val: string) => void;
  imageUrl: string;
  setImageUrl: (val: string) => void;
  productLogs: LogEntry[];
  loadingLogs: boolean;
  imageFile: File | null;
  setImageFile: (file: File | null) => void;
  imagePreview: string | null;
  setImagePreview: (preview: string | null) => void;
  formError: string;
  setFormError: (err: string) => void;
  saving: boolean;
  deleting: boolean;
  cameFromView: boolean;
  isConfirmOpen: boolean;
  setIsConfirmOpen: (open: boolean) => void;
  productNameToDelete: string;
  cropperFile: File | null;
  isCropperOpen: boolean;
  setIsCropperOpen: (open: boolean) => void;
  confirmAction: "activate" | "deactivate";
  productActive: boolean;
  handleOpenAddModal: () => void;
  handleOpenEditModal: (product: Product) => void;
  handleOpenViewModal: (product: Product) => void;
  handleTriggerDelete: (id: string, name: string) => void;
  handleTriggerReactivate: (id: string, name: string) => void;
  handleDelete: () => Promise<void>;
  handleReactivate: (product: Product) => Promise<void>;
  handleConfirmAction: () => Promise<void>;
  handleFileChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  handleCropComplete: (croppedFile: File) => void;
  handleRemoveImage: () => void;
  handleSubmit: (e: React.FormEvent) => Promise<void>;
  categories: string[];
}
